# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180622_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='pointtypes',
        ),
        migrations.AddField(
            model_name='point',
            name='pointtypes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.PointType'),
        ),
    ]
