# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 19:11
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180730_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='audioFile',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=app.models.audioFileLocation),
        ),
        migrations.AlterField(
            model_name='point',
            name='description',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
