# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 17:16
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180806_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileUpload', models.FileField(null=True, upload_to=app.models.audioFileLocation)),
            ],
        ),
    ]
