# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='fileUpload',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
