# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-13 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180806_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
