# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180817_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
