# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_location_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='polygon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Polygon'),
        ),
    ]
