# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-15 00:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_auto_20180817_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ManyToManyField(related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
