# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-15 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_location_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='user',
            new_name='users',
        ),
    ]
